name: Publish to (Test)PyPI on tag

on:
  push:
    tags:
      - 'v*'  # any tag that starts with v

permissions:
  contents: read

jobs:
  build:
    name: Build sdist & wheel
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine
      - name: Build
        run: python -m build
      - name: Verify metadata
        run: twine check dist/*
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  publish:
    name: Publish to (Test)PyPI
    needs: build
    runs-on: ubuntu-latest
    # OIDC is required for Trusted Publishing
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      # Decide TestPyPI vs PyPI based on tag
      - name: Set index based on tag
        id: idx
        run: |
          TAG="${GITHUB_REF_NAME}"
          if [[ "$TAG" =~ [ab]|rc ]]; then
            echo "repo_url=https://test.pypi.org/legacy/" >> $GITHUB_OUTPUT
          else
            echo "repo_url=" >> $GITHUB_OUTPUT
          fi
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages: dist/*
          # empty repo_url -> PyPI, otherwise TestPyPI
          repository-url: ${{ steps.idx.outputs.repo_url }}
